feat: python script to read clients attributes from perun rpc and write them to mongoDB
CESNET/spreg-satosa-sync pull request #1
Opened 2021-11-15 09:48 UTC by xpavlic

python script to read clients attributes from perun rpc and write them to mongoDB

2021-11-15 10:08 UTC, melanger requested changes

2021-11-15 10:08 UTC, melanger commented on rpc_to_mongo_db.py
> +            collection.delete_one({"client_id": client_id})
Can you do `delete_many` for all clients where `client_id not in {present_client_ids}` instead?

2021-11-15 10:08 UTC, melanger commented on rpc_to_mongo_db.py
> +                if not compare_two_lists(value, result[key]):
I think you don't have to check if the new value is different, you can run the update anyway.

2021-11-15 10:08 UTC, melanger commented on rpc_to_mongo_db.py
> +                    collection.update_one({"client_id": result["client_id"]},
This is exactly the same as line 87 and I think it has the same effect as line 94 (you don't need the `"$set"` key for doing simple updates).

Therefore I think you can just remove all `if`s and the loop and just update all they keys in one command (e.g. `collection.update_one({"client_id": result["client_id"]}, attributes_dictionary)`)

2021-11-15 10:08 UTC, melanger commented on rpc_to_mongo_db.py
> +    if result is None:
Instead of this function, you can use `replace_once` with `upsert: true` (see https://docs.mongodb.com/manual/reference/method/db.collection.replaceOne/)

2021-11-15 11:06 UTC, melanger commented on rpc_to_mongo_db.py
> +    connection_string = cfg["database"]["dialect+driver"] + "://" + cfg["database"]["user"] + ":" + \
Make the whole `connection_string` a configuration option, instead of the single options. This way a replication set can be used instead of a single host, parameters may be added etc.

2021-11-15 11:10 UTC, melanger commented on config_template.yml
> +  client_secret: "urn:perun:facility:attribute-def:def:OIDCClientSecret"
`client_secret` is encrypted in Perun, so you need to decrypt it using a key from config (see https://github.com/CESNET/spreg_oidc_metadata_sync/blob/5e28dd574ef3cbf79f25737ba1fd867ecddac0fb/src/main/java/cz/muni/ics/oidc/ToOidcSynchronizer.java#L331)

2021-11-15 11:14 UTC, melanger commented on rpc_to_mongo_db.py
> +    rpc_facilities = rpc_url + "facilitiesManager/getFacilitiesByAttribute?attributeName=urn:perun:facility:attribute-def:def:rpType&attributeValue=satosa"
use `searcherManager/getFacilities` instead and search by both `rpType` and `proxyIdentifier` which has to be equal to a value from config (entity ID of IdP or proxy). This is needed because on some Perun instances there are two independent IdPs/proxies.

2021-11-18 12:50 UTC, melanger requested changes
AES decryption seems OK, the mitreID implementation uses `AES/ECB/PKCS5PADDING`, so this should be all right.

2021-11-18 12:50 UTC, melanger commented on rpc_to_mongo_db.py
> +        cfg["attributes"]["proxy_identifier"] + "=" + cfg["proxy_identifier_value"]
I think the correct format for passing named keys is `url?array[key1]=value1&array[key2]=value2`, therefore:
```suggestion
    rpc_facilities = "{}searcherManager/getFacilities?attributesWithSearchingValues[{}]={}&attributesWithSearchingValues[{}]={}".format(rpc_url, cfg["attributes"]["rp_type"], cfg["rp_type_attr_value"], cfg["attributes"]["proxy_identifier"], cfg["proxy_identifier_value"])
```

2021-11-18 12:50 UTC, melanger commented on rpc_to_mongo_db.py
> +                    result[key] = decrypt_secret(attr["value"], cfg["encryption_key"])
```suggestion
                    result[key] = None if client_secret is None or client_secret == "null" else decrypt_secret(attr["value"], cfg["encryption_key"])
```

2021-11-18 12:50 UTC, melanger commented on rpc_to_mongo_db.py
> +        return None
```suggestion
```

2021-11-18 22:26 UTC, melanger requested changes
Fails on the first RPC call with a 401 Authorization required, some more changes might be needed

2021-11-18 22:26 UTC, melanger commented on rpc_to_mongo_db.py
> +    resp = requests.get(rpc_facilities, data={}, auth=(rpc_username, rpc_password))
```suggestion
    rpc_facilities = "{}json/searcher/getFacilities".format(rpc_url)
    rpc_username = cfg["rpc"]["perun_user"]
    rpc_password = cfg["rpc"]["perun_password"]
    resp = requests.post(
        rpc_facilities,
        json={
            "attributesWithSearchingValues": {
                cfg["attributes"]["rp_type"]: cfg["rp_type_attr_value"],
                cfg["attributes"]["proxy_identifier"]: cfg["proxy_identifier_value"],
            }
        },
        auth=(rpc_username, rpc_password),
    )
```

2021-11-18 22:26 UTC, melanger commented on requirements.txt
> +pymongo~=3.12.1
```suggestion
pycryptodome~=3.11.0
pymongo~=3.12.1
```

2021-11-19 09:42 UTC, melanger requested changes

2021-11-26 16:26 UTC, melanger commented on rpc_to_mongo_db.py
> +    cipher = AES.new(encryption_key, AES.MODE_ECB)
```suggestion
    cipher = AES.new(encryption_key.encode(), AES.MODE_ECB)
```

2021-11-26 16:55 UTC, melanger requested changes

2021-11-26 16:55 UTC, melanger commented on rpc_to_mongo_db.py
> +        collection.replace_one({"client_id": attrs_dict["client_id"]}, attrs_dict, True)
please add logging (e.g. "processing {client_id}")

2021-11-26 16:55 UTC, melanger commented on rpc_to_mongo_db.py
> +        collection.replace_one({"client_id": attrs_dict["client_id"]}, attrs_dict, True)
and test whether replace was successful

2021-11-26 16:55 UTC, melanger commented on rpc_to_mongo_db.py
> +    collection.delete_many({"client_id": {"$nin": present_client_ids}})
check how many clients were deleted, add some logging

2021-11-26 16:55 UTC, melanger commented on rpc_to_mongo_db.py
> +def unpad(s):
use [Crypto.Util.Padding.unpad](https://www.pycryptodome.org/en/latest/src/util/util.html#Crypto.Util.Padding.unpad)

2021-11-26 16:55 UTC, melanger commented on rpc_to_mongo_db.py
> +
```suggestion
```

Not used?

2021-11-26 16:55 UTC, melanger commented on config_template.yml
> +  grant_types: "urn:perun:facility:attribute-def:def:OIDCGrantTypes"
Instead of grant types attribute, we now have a "flow types" attribute (authorization/implicit/device/hybrid), and the grant types are computed (see https://github.com/CESNET/spreg_oidc_metadata_sync/blob/ea24158809fa5b61619d2f4dc1c601c21d3e807e/src/main/java/cz/muni/ics/oidc/ToOidcSynchronizer.java#L375)
Please replicate the same logic here. In the config, use flow_types instead of grant_types. You also need to add grant type `"refresh_token"` when the `issue_refresh_tokens` attribute is `true`.

2021-11-26 16:55 UTC, melanger commented on config_template.yml
> +  grant_types: "urn:perun:facility:attribute-def:def:OIDCGrantTypes"
Also response_types should be computed from grant types.

2021-11-26 16:55 UTC, melanger commented on config_template.yml
> +encryption_key: "secret"
```suggestion
encryption_key: "secret"

static_attributes:
  subject_type: public
  application_type: web
  token_endpoint_auth_method: none
```

We will need to set some global (static) attributes which cannot be edited in SP reg app, but SATOSA needs them to be set. This could be the config, just key:value pairs, which would be added to the client settings (before values from Perun, so that if the same attribute is here and in Perun, the value from Perun overrides the static value).

2021-11-26 16:55 UTC, melanger commented on config_template.yml
> +  name: "urn:perun:facility:attribute-def:def:serviceName"
Name can be a string or a map language:translation. If it is a string, save it into the "client_name" property of the client (currently it is saved into 'name').

When it is a map, create multiple items, for each value in the map. Use English or Czech or first other language as the default, add all others with the language key.
For this value in Perun:
```
{
  "en": "English name",
  "cs": "Český název"
}
```
do:
```
"client_name": "English version",
"client_name#cs": "Český název"
```
or this would be also fine:
```
"client_name": "English version",
"client_name#en": "English version",
"client_name#cs": "Český název"
```
This is the required format for SATOSA - the [OIDC dynamic registration request format](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest).

2021-11-26 16:58 UTC, melanger commented on rpc_to_mongo_db.py
> +    collection.delete_many({"client_id": {"$nin": present_client_ids}})
also make this configurable (on/off), by default do not delete any clients

2021-11-29 11:27 UTC, xpavlic commented on rpc_to_mongo_db.py
> +        collection.replace_one({"client_id": attrs_dict["client_id"]}, attrs_dict, True)
This should be always successful, because of upsert. If document with given client_id is not found, it is inserted as new one.

2021-11-29 11:33 UTC, melanger commented on rpc_to_mongo_db.py
> +        collection.replace_one({"client_id": attrs_dict["client_id"]}, attrs_dict, True)
There can be a general error, like insufficient permissions. Also, the `replace_one` method should return info whether the facility was replaced or inserted (like `{"acknowledged" : true,"matchedCount" : 0,"modifiedCount" : 0,"upsertedId" : 4}`) which is very useful for debugging. The current version of rpc_to_mongo_db.py does not print anything.

2021-11-30 10:00 UTC, melanger requested changes
Client secret decryption works correctly. I have added some suggestions based on https://openid.net/specs/openid-connect-registration-1_0-29.html and https://github.com/IdentityPython/oidc-op/blob/v2.3.0/docs/source/contents/conf.rst#clients, you can accept (commit) them directly on GitHub.

2021-11-30 10:02 UTC, melanger commented
Please also run [prettier](https://prettier.io/) (e.g. `npx prettier --write .`) and [black](https://github.com/psf/black).

2021-11-30 11:53 UTC, melanger commented on config_template.yml
> +  flow_types: "urn:perun:facility:attribute-def:def:OIDCGrantTypes"
```suggestion
  flow_types: "urn:perun:facility:attribute-def:def:OIDCFlowTypes"
```

2021-12-01 08:51 UTC, melanger requested changes
Just one minor bug caused by an incomplete suggestion + removed obsolete attributes from example config. Otherwise it is good to go, thanks.

2021-12-01 08:51 UTC, melanger commented on rpc_to_mongo_db.py
> +                        result["client_name"] = attr["value"]
```suggestion
                        result[key] = attr["value"]
```

2021-12-01 08:51 UTC, melanger commented on rpc_to_mongo_db.py
> +                elif key not in ["proxy_identifier", "rp_type"]:
```suggestion
                elif key not in ["master_proxy_identifier", "proxy_identifier", "rp_type"]:
```

2021-12-01 08:51 UTC, melanger commented on config_template.yml
> +  is_oidc: "urn:perun:facility:attribute-def:def:isOidc"
```suggestion
```

2021-12-01 08:51 UTC, melanger commented on config_template.yml
> +  introspection: "urn:perun:facility:attribute-def:def:OIDCAllowIntrospection"
```suggestion
```

2021-12-01 09:10 UTC, melanger requested changes

2021-12-01 09:10 UTC, melanger commented on rpc_to_mongo_db.py
> +                            result["client_name#" + lan] = trans
```suggestion
                            if key not in result:
                                result[key] = trans
                            result[key + "#" + lan] = trans
```

2021-12-01 09:10 UTC, melanger commented on rpc_to_mongo_db.py
> +                if key in result.keys():
```suggestion
                if key in result:
```
With dictionaries, `x in y` does the same thing as `x in y.keys()`

2021-12-01 10:17 UTC, melanger approved these changes

2021-12-01 10:17 UTC, merged